cryptopals_c: hex2b64.c File Reference
hex2b64.c File Reference
Implementation of hex-to-Base64 conversion helpers.
#include "hex2b64.h"
#include <ctype.h>
#include <stdio.h>
Functions
static int hex_value (int c)
Convert a single hexadecimal character into its integer value.
static void encode_base64_chars (const unsigned char *in, size_t len, char encoded[4])
Produce four Base64 characters from up to three bytes.
static void encode_base64_block (const unsigned char *in, size_t len, FILE *out)
Write a Base64 block derived from up to three input bytes.
int hex2b64_stream (FILE *in, FILE *out)
Implementation of hex2b64_stream().
int hex2b64_buffer (const unsigned char *hex, size_t hex_len, unsigned char *out, size_t out_cap, size_t *out_len)
Implementation of hex2b64_buffer().
Variables
static const char b64_table []
Detailed Description
Implementation of hex-to-Base64 conversion helpers.
Definition in file hex2b64.c.
Function Documentation
encode_base64_block()
static void encode_base64_block (const unsigned char * in, size_t len, FILE * out) static
Write a Base64 block derived from up to three input bytes.
Parameters
in Source bytes.
len Number of source bytes.
out Output stream that receives four Base64 characters.
Definition at line 59 of file hex2b64.c.
References encode_base64_chars().
encode_base64_chars()
static void encode_base64_chars (const unsigned char * in, size_t len, char encoded[4]) static
Produce four Base64 characters from up to three bytes.
Parameters
in Input bytes (padded implicitly with zeros).
len Number of valid bytes (1-3).
encoded Destination for the four encoded characters.
Definition at line 36 of file hex2b64.c.
References b64_table.
hex2b64_buffer()
int hex2b64_buffer (const unsigned char * hex, size_t hex_len, unsigned char * out, size_t out_cap, size_t * out_len)
Implementation of hex2b64_buffer().
Convert a memory buffer of hexadecimal characters into Base64.
Definition at line 123 of file hex2b64.c.
References encode_base64_chars(), and hex_value().
hex2b64_stream()
int hex2b64_stream (FILE * in, FILE * out)
Implementation of hex2b64_stream().
Convert hexadecimal text read from a stream into Base64.
Definition at line 70 of file hex2b64.c.
References encode_base64_block(), and hex_value().
hex_value()
static int hex_value (int c) static
Convert a single hexadecimal character into its integer value.
Parameters
c Character to convert.
Returns
0-15 for valid hex digits, or -1 when c is not hexadecimal.
Definition at line 22 of file hex2b64.c.
Variable Documentation
b64_table
const char b64_table[] static
Initial value:
=
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789+/"
Definition at line 11 of file hex2b64.c.