cryptopals_c: test_score_english_hex.c File Reference
test_score_english_hex.c File Reference
#include "score_english_hex.h"
#include "utest.h"
Functions
UTEST (score_english_hex, english_phrase_beats_random)
UTEST (score_english_hex, rejects_invalid_hex_character)
UTEST (score_english_hex, rejects_odd_length)
UTEST (score_english_hex, rejects_non_printable_bytes)
UTEST_MAIN ()
Function Documentation
UTEST() [1/4]
UTEST (score_english_hex , english_phrase_beats_random)
Definition at line 8 of file test_score_english_hex.c.
References ASSERT_GT, and score_english_hex().
UTEST() [2/4]
UTEST (score_english_hex , rejects_invalid_hex_character)
Definition at line 16 of file test_score_english_hex.c.
References ASSERT_LT, and score_english_hex().
UTEST() [3/4]
UTEST (score_english_hex , rejects_non_printable_bytes)
Definition at line 28 of file test_score_english_hex.c.
References ASSERT_GT, ASSERT_LT, and score_english_hex().
UTEST() [4/4]
UTEST (score_english_hex , rejects_odd_length)
Definition at line 22 of file test_score_english_hex.c.
References ASSERT_LT, and score_english_hex().
UTEST_MAIN()
UTEST_MAIN ()