cryptopals_c: test_hex2b64.c File Reference
test_hex2b64.c File Reference
#include <stdio.h>
#include <string.h>
#include "hex2b64.h"
#include "utest.h"
Functions
static int convert_hex_string (const char *hex, char *out, size_t out_cap)
static int convert_hex_buffer (const char *hex, unsigned char *out, size_t out_cap, size_t *out_len)
UTEST (stream, hello_world_plain)
UTEST (stream, ignores_whitespace)
UTEST (stream, mixed_case_hex)
UTEST (stream_edge, empty_input)
UTEST (stream_edge, whitespace_only)
UTEST (stream_edge, single_byte)
UTEST (stream_edge, two_bytes)
UTEST (stream_edge, three_bytes)
UTEST (stream_edge, odd_number_of_digits_is_error)
UTEST (stream_edge, invalid_char_in_middle)
UTEST (stream_edge, invalid_first_char)
UTEST (stream_edge, many_bytes_sanity)
UTEST (buffer, hello_world_plain)
UTEST (buffer, ignores_whitespace)
UTEST (buffer, empty_input)
UTEST (buffer_edge, odd_digits_error)
UTEST (buffer_edge, invalid_character)
UTEST (buffer_edge, insufficient_output_capacity)
UTEST_MAIN ()
Function Documentation
convert_hex_buffer()
static int convert_hex_buffer (const char * hex, unsigned char * out, size_t out_cap, size_t * out_len) static
Definition at line 43 of file test_hex2b64.c.
References hex2b64_buffer().
convert_hex_string()
static int convert_hex_string (const char * hex, char * out, size_t out_cap) static
Definition at line 14 of file test_hex2b64.c.
References hex2b64_stream().
UTEST() [1/18]
UTEST (buffer , empty_input)
Definition at line 192 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_buffer().
UTEST() [2/18]
UTEST (buffer , hello_world_plain)
Definition at line 167 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_buffer().
UTEST() [3/18]
UTEST (buffer , ignores_whitespace)
Definition at line 180 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_buffer().
UTEST() [4/18]
UTEST (buffer_edge , insufficient_output_capacity)
Definition at line 225 of file test_hex2b64.c.
References ASSERT_NE, and convert_hex_buffer().
UTEST() [5/18]
UTEST (buffer_edge , invalid_character)
Definition at line 215 of file test_hex2b64.c.
References ASSERT_NE, and convert_hex_buffer().
UTEST() [6/18]
UTEST (buffer_edge , odd_digits_error)
Definition at line 205 of file test_hex2b64.c.
References ASSERT_NE, and convert_hex_buffer().
UTEST() [7/18]
UTEST (stream , hello_world_plain)
Definition at line 56 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [8/18]
UTEST (stream , ignores_whitespace)
Definition at line 64 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [9/18]
UTEST (stream , mixed_case_hex)
Definition at line 73 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [10/18]
UTEST (stream_edge , empty_input)
Definition at line 83 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [11/18]
UTEST (stream_edge , invalid_char_in_middle)
Definition at line 130 of file test_hex2b64.c.
References ASSERT_NE, and convert_hex_string().
UTEST() [12/18]
UTEST (stream_edge , invalid_first_char)
Definition at line 137 of file test_hex2b64.c.
References ASSERT_NE, and convert_hex_string().
UTEST() [13/18]
UTEST (stream_edge , many_bytes_sanity)
Definition at line 144 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_GT, and convert_hex_string().
UTEST() [14/18]
UTEST (stream_edge , odd_number_of_digits_is_error)
Definition at line 123 of file test_hex2b64.c.
References ASSERT_NE, and convert_hex_string().
UTEST() [15/18]
UTEST (stream_edge , single_byte)
Definition at line 99 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [16/18]
UTEST (stream_edge , three_bytes)
Definition at line 115 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [17/18]
UTEST (stream_edge , two_bytes)
Definition at line 107 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST() [18/18]
UTEST (stream_edge , whitespace_only)
Definition at line 91 of file test_hex2b64.c.
References ASSERT_EQ, ASSERT_STREQ, and convert_hex_string().
UTEST_MAIN()
UTEST_MAIN ()