cryptopals_c: test_fixed_xor.c File Reference
test_fixed_xor.c File Reference
#include <stdio.h>
#include <string.h>
#include "fixed_xor.h"
#include "utest.h"
Functions
UTEST (fixed_xor_buffers, simple_values)
UTEST (fixed_xor_buffers, zero_length_is_ok)
UTEST (fixed_xor_buffers, allows_output_alias)
UTEST (fixed_xor_buffers, null_pointer_rejected)
UTEST (fixed_xor_stream, processes_two_buffers)
UTEST (fixed_xor_stream, empty_input_ok)
UTEST (fixed_xor_stream, odd_length_input_fails)
UTEST (fixed_xor_stream, large_input_triggers_growth)
UTEST (fixed_xor_status_string, returns_text)
UTEST_MAIN ()
Function Documentation
UTEST() [1/9]
UTEST (fixed_xor_buffers , allows_output_alias)
Definition at line 33 of file test_fixed_xor.c.
References ASSERT_EQ, fixed_xor_buffers(), and FIXED_XOR_OK.
UTEST() [2/9]
UTEST (fixed_xor_buffers , null_pointer_rejected)
Definition at line 45 of file test_fixed_xor.c.
References ASSERT_EQ, fixed_xor_buffers(), and FIXED_XOR_ERR_ARGS.
UTEST() [3/9]
UTEST (fixed_xor_buffers , simple_values)
Definition at line 11 of file test_fixed_xor.c.
References ASSERT_EQ, fixed_xor_buffers(), and FIXED_XOR_OK.
UTEST() [4/9]
UTEST (fixed_xor_buffers , zero_length_is_ok)
Definition at line 24 of file test_fixed_xor.c.
References ASSERT_EQ, fixed_xor_buffers(), and FIXED_XOR_OK.
UTEST() [5/9]
UTEST (fixed_xor_status_string , returns_text)
Definition at line 152 of file test_fixed_xor.c.
References ASSERT_STREQ, FIXED_XOR_ERR_ARGS, FIXED_XOR_ERR_IO, FIXED_XOR_ERR_ODD_INPUT, FIXED_XOR_ERR_OOM, FIXED_XOR_OK, and fixed_xor_status_string().
UTEST() [6/9]
UTEST (fixed_xor_stream , empty_input_ok)
Definition at line 86 of file test_fixed_xor.c.
References ASSERT_EQ, ASSERT_TRUE, FIXED_XOR_OK, and fixed_xor_stream().
UTEST() [7/9]
UTEST (fixed_xor_stream , large_input_triggers_growth)
Definition at line 120 of file test_fixed_xor.c.
References ASSERT_EQ, ASSERT_TRUE, FIXED_XOR_OK, and fixed_xor_stream().
UTEST() [8/9]
UTEST (fixed_xor_stream , odd_length_input_fails)
Definition at line 103 of file test_fixed_xor.c.
References ASSERT_EQ, ASSERT_TRUE, FIXED_XOR_ERR_ODD_INPUT, and fixed_xor_stream().
UTEST() [9/9]
UTEST (fixed_xor_stream , processes_two_buffers)
Definition at line 60 of file test_fixed_xor.c.
References ASSERT_EQ, ASSERT_TRUE, FIXED_XOR_OK, and fixed_xor_stream().
UTEST_MAIN()
UTEST_MAIN ()