cryptopals_c: utest.h File Reference
utest.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <inttypes.h>
#include <unistd.h>
Data Structures
struct utest_test_state_s
struct utest_state_s
Macros
#define UTEST_C_FUNC
#define UTEST_TEST_PASSED (0)
#define UTEST_TEST_FAILURE (1)
#define UTEST_TEST_SKIPPED (2)
#define UTEST_ATTRIBUTE(a) __attribute__((a))
#define UTEST_PRId64 PRId64
#define UTEST_PRIu64 PRIu64
#define UTEST_INLINE inline
#define UTEST_INITIALIZER(f)
#define UTEST_CAST(type, x) ((type)(x))
#define UTEST_PTR_CAST(type, x) ((type)(x))
#define UTEST_EXTERN extern
#define UTEST_NULL 0
#define UTEST_COLOUR_OUTPUT() (isatty(STDOUT_FILENO))
#define UTEST_UNUSED UTEST_ATTRIBUTE(unused)
#define UTEST_PRINTF(...)
#define UTEST_SNPRINTF(...) snprintf(__VA_ARGS__)
#define utest_type_printer(...) UTEST_PRINTF("undef")
#define UTEST_SURPRESS_WARNING_BEGIN
#define UTEST_SURPRESS_WARNING_END
#define UTEST_AUTO(x) __typeof__(x + 0)
#define UTEST_STRNCMP(x, y, size) strncmp(x, y, size)
#define UTEST_STRNCPY(x, y, size) strncpy(x, y, size)
#define UTEST_SKIP(msg)
#define UTEST_COND(x, y, cond, msg, is_assert)
#define EXPECT_EQ(x, y) UTEST_COND(x, y, ==, "", 0)
#define EXPECT_EQ_MSG(x, y, msg) UTEST_COND(x, y, ==, msg, 0)
#define ASSERT_EQ(x, y) UTEST_COND(x, y, ==, "", 1)
#define ASSERT_EQ_MSG(x, y, msg) UTEST_COND(x, y, ==, msg, 1)
#define EXPECT_NE(x, y) UTEST_COND(x, y, !=, "", 0)
#define EXPECT_NE_MSG(x, y, msg) UTEST_COND(x, y, !=, msg, 0)
#define ASSERT_NE(x, y) UTEST_COND(x, y, !=, "", 1)
#define ASSERT_NE_MSG(x, y, msg) UTEST_COND(x, y, !=, msg, 1)
#define EXPECT_LT(x, y) UTEST_COND(x, y, <, "", 0)
#define EXPECT_LT_MSG(x, y, msg) UTEST_COND(x, y, <, msg, 0)
#define ASSERT_LT(x, y) UTEST_COND(x, y, <, "", 1)
#define ASSERT_LT_MSG(x, y, msg) UTEST_COND(x, y, <, msg, 1)
#define EXPECT_LE(x, y) UTEST_COND(x, y, <=, "", 0)
#define EXPECT_LE_MSG(x, y, msg) UTEST_COND(x, y, <=, msg, 0)
#define ASSERT_LE(x, y) UTEST_COND(x, y, <=, "", 1)
#define ASSERT_LE_MSG(x, y, msg) UTEST_COND(x, y, <=, msg, 1)
#define EXPECT_GT(x, y) UTEST_COND(x, y, >, "", 0)
#define EXPECT_GT_MSG(x, y, msg) UTEST_COND(x, y, >, msg, 0)
#define ASSERT_GT(x, y) UTEST_COND(x, y, >, "", 1)
#define ASSERT_GT_MSG(x, y, msg) UTEST_COND(x, y, >, msg, 1)
#define EXPECT_GE(x, y) UTEST_COND(x, y, >=, "", 0)
#define EXPECT_GE_MSG(x, y, msg) UTEST_COND(x, y, >=, msg, 0)
#define ASSERT_GE(x, y) UTEST_COND(x, y, >=, "", 1)
#define ASSERT_GE_MSG(x, y, msg) UTEST_COND(x, y, >=, msg, 1)
#define UTEST_TRUE(x, msg, is_assert)
#define EXPECT_TRUE(x) UTEST_TRUE(x, "", 0)
#define EXPECT_TRUE_MSG(x, msg) UTEST_TRUE(x, msg, 0)
#define ASSERT_TRUE(x) UTEST_TRUE(x, "", 1)
#define ASSERT_TRUE_MSG(x, msg) UTEST_TRUE(x, msg, 1)
#define UTEST_FALSE(x, msg, is_assert)
#define EXPECT_FALSE(x) UTEST_FALSE(x, "", 0)
#define EXPECT_FALSE_MSG(x, msg) UTEST_FALSE(x, msg, 0)
#define ASSERT_FALSE(x) UTEST_FALSE(x, "", 1)
#define ASSERT_FALSE_MSG(x, msg) UTEST_FALSE(x, msg, 1)
#define UTEST_STREQ(x, y, msg, is_assert)
#define EXPECT_STREQ(x, y) UTEST_STREQ(x, y, "", 0)
#define EXPECT_STREQ_MSG(x, y, msg) UTEST_STREQ(x, y, msg, 0)
#define ASSERT_STREQ(x, y) UTEST_STREQ(x, y, "", 1)
#define ASSERT_STREQ_MSG(x, y, msg) UTEST_STREQ(x, y, msg, 1)
#define UTEST_STRNE(x, y, msg, is_assert)
#define EXPECT_STRNE(x, y) UTEST_STRNE(x, y, "", 0)
#define EXPECT_STRNE_MSG(x, y, msg) UTEST_STRNE(x, y, msg, 0)
#define ASSERT_STRNE(x, y) UTEST_STRNE(x, y, "", 1)
#define ASSERT_STRNE_MSG(x, y, msg) UTEST_STRNE(x, y, msg, 1)
#define UTEST_STRNEQ(x, y, n, msg, is_assert)
#define EXPECT_STRNEQ(x, y, n) UTEST_STRNEQ(x, y, n, "", 0)
#define EXPECT_STRNEQ_MSG(x, y, n, msg) UTEST_STRNEQ(x, y, n, msg, 0)
#define ASSERT_STRNEQ(x, y, n) UTEST_STRNEQ(x, y, n, "", 1)
#define ASSERT_STRNEQ_MSG(x, y, n, msg) UTEST_STRNEQ(x, y, n, msg, 1)
#define UTEST_STRNNE(x, y, n, msg, is_assert)
#define EXPECT_STRNNE(x, y, n) UTEST_STRNNE(x, y, n, "", 0)
#define EXPECT_STRNNE_MSG(x, y, n, msg) UTEST_STRNNE(x, y, n, msg, 0)
#define ASSERT_STRNNE(x, y, n) UTEST_STRNNE(x, y, n, "", 1)
#define ASSERT_STRNNE_MSG(x, y, n, msg) UTEST_STRNNE(x, y, n, msg, 1)
#define UTEST_NEAR(x, y, epsilon, msg, is_assert)
#define EXPECT_NEAR(x, y, epsilon) UTEST_NEAR(x, y, epsilon, "", 0)
#define EXPECT_NEAR_MSG(x, y, epsilon, msg) UTEST_NEAR(x, y, epsilon, msg, 0)
#define ASSERT_NEAR(x, y, epsilon) UTEST_NEAR(x, y, epsilon, "", 1)
#define ASSERT_NEAR_MSG(x, y, epsilon, msg) UTEST_NEAR(x, y, epsilon, msg, 1)
#define UTEST_SURPRESS_WARNINGS_BEGIN
#define UTEST_SURPRESS_WARNINGS_END
#define UTEST(SET, NAME)
#define UTEST_F_SETUP(FIXTURE)
#define UTEST_F_TEARDOWN(FIXTURE)
#define UTEST_F(FIXTURE, NAME)
#define UTEST_I_SETUP(FIXTURE)
#define UTEST_I_TEARDOWN(FIXTURE)
#define UTEST_I(FIXTURE, NAME, INDEX)
#define UTEST_STATE() struct utest_state_s utest_state = {0, 0, 0}
#define UTEST_MAIN()
Typedefs
typedef int64_t utest_int64_t
typedef uint64_t utest_uint64_t
typedef uint32_t utest_uint32_t
typedef void(* utest_testcase_t) (int *, size_t)
Functions
static void * utest_realloc (void *const pointer, size_t new_size)
static utest_int64_t utest_mul_div (const utest_int64_t value, const utest_int64_t numer, const utest_int64_t denom)
static utest_int64_t utest_ns (void)
UTEST_WEAK double utest_fabs (double d)
UTEST_WEAK int utest_isnan (double d)
UTEST_WEAK int utest_should_filter_test (const char *filter, const char *testcase)
static FILE * utest_fopen (const char *filename, const char *mode)
static int utest_main (int argc, const char *const argv[])
Variables
struct utest_state_s utest_state
Data Structure Documentation
utest_test_state_s
struct utest_test_state_s
Definition at line 381 of file utest.h.
Data Fields
utest_testcase_t func
size_t index
char * name
utest_state_s
struct utest_state_s
Definition at line 387 of file utest.h.
Data Fields
FILE * output
struct utest_test_state_s * tests
size_t tests_length
Macro Definition Documentation
ASSERT_EQ
#define ASSERT_EQ (x, y) UTEST_COND(x, y, ==, "", 1)
Definition at line 839 of file utest.h.
ASSERT_EQ_MSG
#define ASSERT_EQ_MSG (x, y, msg) UTEST_COND(x, y, ==, msg, 1)
Definition at line 840 of file utest.h.
ASSERT_FALSE
#define ASSERT_FALSE (x) UTEST_FALSE(x, "", 1)
Definition at line 912 of file utest.h.
ASSERT_FALSE_MSG
#define ASSERT_FALSE_MSG (x, msg) UTEST_FALSE(x, msg, 1)
Definition at line 913 of file utest.h.
ASSERT_GE
#define ASSERT_GE (x, y) UTEST_COND(x, y, >=, "", 1)
Definition at line 864 of file utest.h.
ASSERT_GE_MSG
#define ASSERT_GE_MSG (x, y, msg) UTEST_COND(x, y, >=, msg, 1)
Definition at line 865 of file utest.h.
ASSERT_GT
#define ASSERT_GT (x, y) UTEST_COND(x, y, >, "", 1)
Definition at line 859 of file utest.h.
ASSERT_GT_MSG
#define ASSERT_GT_MSG (x, y, msg) UTEST_COND(x, y, >, msg, 1)
Definition at line 860 of file utest.h.
ASSERT_LE
#define ASSERT_LE (x, y) UTEST_COND(x, y, <=, "", 1)
Definition at line 854 of file utest.h.
ASSERT_LE_MSG
#define ASSERT_LE_MSG (x, y, msg) UTEST_COND(x, y, <=, msg, 1)
Definition at line 855 of file utest.h.
ASSERT_LT
#define ASSERT_LT (x, y) UTEST_COND(x, y, <, "", 1)
Definition at line 849 of file utest.h.
ASSERT_LT_MSG
#define ASSERT_LT_MSG (x, y, msg) UTEST_COND(x, y, <, msg, 1)
Definition at line 850 of file utest.h.
ASSERT_NE
#define ASSERT_NE (x, y) UTEST_COND(x, y, !=, "", 1)
Definition at line 844 of file utest.h.
ASSERT_NE_MSG
#define ASSERT_NE_MSG (x, y, msg) UTEST_COND(x, y, !=, msg, 1)
Definition at line 845 of file utest.h.
ASSERT_NEAR
#define ASSERT_NEAR (x, y, epsilon) UTEST_NEAR(x, y, epsilon, "", 1)
Definition at line 1043 of file utest.h.
ASSERT_NEAR_MSG
#define ASSERT_NEAR_MSG (x, y, epsilon, msg) UTEST_NEAR(x, y, epsilon, msg, 1)
Definition at line 1044 of file utest.h.
ASSERT_STREQ
#define ASSERT_STREQ (x, y) UTEST_STREQ(x, y, "", 1)
Definition at line 938 of file utest.h.
ASSERT_STREQ_MSG
#define ASSERT_STREQ_MSG (x, y, msg) UTEST_STREQ(x, y, msg, 1)
Definition at line 939 of file utest.h.
ASSERT_STRNE
#define ASSERT_STRNE (x, y) UTEST_STRNE(x, y, "", 1)
Definition at line 964 of file utest.h.
ASSERT_STRNE_MSG
#define ASSERT_STRNE_MSG (x, y, msg) UTEST_STRNE(x, y, msg, 1)
Definition at line 965 of file utest.h.
ASSERT_STRNEQ
#define ASSERT_STRNEQ (x, y, n) UTEST_STRNEQ(x, y, n, "", 1)
Definition at line 991 of file utest.h.
ASSERT_STRNEQ_MSG
#define ASSERT_STRNEQ_MSG (x, y, n, msg) UTEST_STRNEQ(x, y, n, msg, 1)
Definition at line 992 of file utest.h.
ASSERT_STRNNE
#define ASSERT_STRNNE (x, y, n) UTEST_STRNNE(x, y, n, "", 1)
Definition at line 1018 of file utest.h.
ASSERT_STRNNE_MSG
#define ASSERT_STRNNE_MSG (x, y, n, msg) UTEST_STRNNE(x, y, n, msg, 1)
Definition at line 1019 of file utest.h.
ASSERT_TRUE
#define ASSERT_TRUE (x) UTEST_TRUE(x, "", 1)
Definition at line 888 of file utest.h.
ASSERT_TRUE_MSG
#define ASSERT_TRUE_MSG (x, msg) UTEST_TRUE(x, msg, 1)
Definition at line 889 of file utest.h.
EXPECT_EQ
#define EXPECT_EQ (x, y) UTEST_COND(x, y, ==, "", 0)
Definition at line 837 of file utest.h.
EXPECT_EQ_MSG
#define EXPECT_EQ_MSG (x, y, msg) UTEST_COND(x, y, ==, msg, 0)
Definition at line 838 of file utest.h.
EXPECT_FALSE
#define EXPECT_FALSE (x) UTEST_FALSE(x, "", 0)
Definition at line 910 of file utest.h.
EXPECT_FALSE_MSG
#define EXPECT_FALSE_MSG (x, msg) UTEST_FALSE(x, msg, 0)
Definition at line 911 of file utest.h.
EXPECT_GE
#define EXPECT_GE (x, y) UTEST_COND(x, y, >=, "", 0)
Definition at line 862 of file utest.h.
EXPECT_GE_MSG
#define EXPECT_GE_MSG (x, y, msg) UTEST_COND(x, y, >=, msg, 0)
Definition at line 863 of file utest.h.
EXPECT_GT
#define EXPECT_GT (x, y) UTEST_COND(x, y, >, "", 0)
Definition at line 857 of file utest.h.
EXPECT_GT_MSG
#define EXPECT_GT_MSG (x, y, msg) UTEST_COND(x, y, >, msg, 0)
Definition at line 858 of file utest.h.
EXPECT_LE
#define EXPECT_LE (x, y) UTEST_COND(x, y, <=, "", 0)
Definition at line 852 of file utest.h.
EXPECT_LE_MSG
#define EXPECT_LE_MSG (x, y, msg) UTEST_COND(x, y, <=, msg, 0)
Definition at line 853 of file utest.h.
EXPECT_LT
#define EXPECT_LT (x, y) UTEST_COND(x, y, <, "", 0)
Definition at line 847 of file utest.h.
EXPECT_LT_MSG
#define EXPECT_LT_MSG (x, y, msg) UTEST_COND(x, y, <, msg, 0)
Definition at line 848 of file utest.h.
EXPECT_NE
#define EXPECT_NE (x, y) UTEST_COND(x, y, !=, "", 0)
Definition at line 842 of file utest.h.
EXPECT_NE_MSG
#define EXPECT_NE_MSG (x, y, msg) UTEST_COND(x, y, !=, msg, 0)
Definition at line 843 of file utest.h.
EXPECT_NEAR
#define EXPECT_NEAR (x, y, epsilon) UTEST_NEAR(x, y, epsilon, "", 0)
Definition at line 1041 of file utest.h.
EXPECT_NEAR_MSG
#define EXPECT_NEAR_MSG (x, y, epsilon, msg) UTEST_NEAR(x, y, epsilon, msg, 0)
Definition at line 1042 of file utest.h.
EXPECT_STREQ
#define EXPECT_STREQ (x, y) UTEST_STREQ(x, y, "", 0)
Definition at line 936 of file utest.h.
EXPECT_STREQ_MSG
#define EXPECT_STREQ_MSG (x, y, msg) UTEST_STREQ(x, y, msg, 0)
Definition at line 937 of file utest.h.
EXPECT_STRNE
#define EXPECT_STRNE (x, y) UTEST_STRNE(x, y, "", 0)
Definition at line 962 of file utest.h.
EXPECT_STRNE_MSG
#define EXPECT_STRNE_MSG (x, y, msg) UTEST_STRNE(x, y, msg, 0)
Definition at line 963 of file utest.h.
EXPECT_STRNEQ
#define EXPECT_STRNEQ (x, y, n) UTEST_STRNEQ(x, y, n, "", 0)
Definition at line 989 of file utest.h.
EXPECT_STRNEQ_MSG
#define EXPECT_STRNEQ_MSG (x, y, n, msg) UTEST_STRNEQ(x, y, n, msg, 0)
Definition at line 990 of file utest.h.
EXPECT_STRNNE
#define EXPECT_STRNNE (x, y, n) UTEST_STRNNE(x, y, n, "", 0)
Definition at line 1016 of file utest.h.
EXPECT_STRNNE_MSG
#define EXPECT_STRNNE_MSG (x, y, n, msg) UTEST_STRNNE(x, y, n, msg, 0)
Definition at line 1017 of file utest.h.
EXPECT_TRUE
#define EXPECT_TRUE (x) UTEST_TRUE(x, "", 0)
Definition at line 886 of file utest.h.
EXPECT_TRUE_MSG
#define EXPECT_TRUE_MSG (x, msg) UTEST_TRUE(x, msg, 0)
Definition at line 887 of file utest.h.
UTEST
#define UTEST (SET, NAME)
Definition at line 1166 of file utest.h.
UTEST_ATTRIBUTE
#define UTEST_ATTRIBUTE (a) __attribute__((a))
Definition at line 137 of file utest.h.
UTEST_AUTO
#define UTEST_AUTO (x) __typeof__(x + 0)
Definition at line 717 of file utest.h.
UTEST_C_FUNC
#define UTEST_C_FUNC
Definition at line 127 of file utest.h.
UTEST_CAST
#define UTEST_CAST (type, x) ((type)(x))
Definition at line 297 of file utest.h.
UTEST_COLOUR_OUTPUT
#define UTEST_COLOUR_OUTPUT () (isatty(STDOUT_FILENO))
Definition at line 320 of file utest.h.
UTEST_COND
#define UTEST_COND (x, y, cond, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    if (!((x)cond(y))) {                                                       \
      UTEST_PRINTF("%s:%i: Failure (Expected " #cond " Actual)", __FILE__,     \
                   __LINE__);                                                  \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF(" Message : %s", msg);                                    \
      }                                                                        \
      UTEST_PRINTF("\n");                                                      \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 818 of file utest.h.
UTEST_EXTERN
#define UTEST_EXTERN extern
Definition at line 299 of file utest.h.
UTEST_F
#define UTEST_F (FIXTURE, NAME)
Definition at line 1210 of file utest.h.
UTEST_F_SETUP
#define UTEST_F_SETUP (FIXTURE)
Value:
  static void utest_f_setup_##FIXTURE(int *utest_result,                       \
                                      struct FIXTURE *utest_fixture)
Definition at line 1202 of file utest.h.
UTEST_F_TEARDOWN
#define UTEST_F_TEARDOWN (FIXTURE)
Value:
  static void utest_f_teardown_##FIXTURE(int *utest_result,                    \
                                         struct FIXTURE *utest_fixture)
Definition at line 1206 of file utest.h.
UTEST_FALSE
#define UTEST_FALSE (x, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const int xEval = !!(x);                                                   \
    if (xEval) {                                                               \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : false\n");                                    \
      UTEST_PRINTF("    Actual : %s\n", (xEval) ? "true" : "false");           \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 891 of file utest.h.
UTEST_I
#define UTEST_I (FIXTURE, NAME, INDEX)
Definition at line 1265 of file utest.h.
UTEST_I_SETUP
#define UTEST_I_SETUP (FIXTURE)
Value:
  static void utest_i_setup_##FIXTURE(                                         \
      int *utest_result, struct FIXTURE *utest_fixture, size_t utest_index)
Definition at line 1257 of file utest.h.
UTEST_I_TEARDOWN
#define UTEST_I_TEARDOWN (FIXTURE)
Value:
  static void utest_i_teardown_##FIXTURE(                                      \
      int *utest_result, struct FIXTURE *utest_fixture, size_t utest_index)
Definition at line 1261 of file utest.h.
UTEST_INITIALIZER
#define UTEST_INITIALIZER (f)
Value:
  static void f(void) UTEST_ATTRIBUTE(constructor);                            \
  static void f(void)
Definition at line 286 of file utest.h.
UTEST_INLINE
#define UTEST_INLINE inline
Definition at line 284 of file utest.h.
UTEST_MAIN
#define UTEST_MAIN ()
Value:
  UTEST_STATE();                                                               \
  int main(int argc, const char *const argv[]) {                               \
    return utest_main(argc, argv);                                             \
  }
Definition at line 1724 of file utest.h.
UTEST_NEAR
#define UTEST_NEAR (x, y, epsilon, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const double diff =                                                        \
        utest_fabs(UTEST_CAST(double, x) - UTEST_CAST(double, y));             \
    if (diff > UTEST_CAST(double, epsilon) || utest_isnan(diff)) {             \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : %f\n", UTEST_CAST(double, x));                \
      UTEST_PRINTF("    Actual : %f\n", UTEST_CAST(double, y));                \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 1021 of file utest.h.
UTEST_NULL
#define UTEST_NULL 0
Definition at line 300 of file utest.h.
UTEST_PRId64
#define UTEST_PRId64 PRId64
Definition at line 212 of file utest.h.
UTEST_PRINTF
#define UTEST_PRINTF (...)
Value:
  if (utest_state.output) {                                                    \
    fprintf(utest_state.output, __VA_ARGS__);                                  \
  }                                                                            \
  printf(__VA_ARGS__)
Definition at line 417 of file utest.h.
UTEST_PRIu64
#define UTEST_PRIu64 PRIu64
Definition at line 213 of file utest.h.
UTEST_PTR_CAST
#define UTEST_PTR_CAST (type, x) ((type)(x))
Definition at line 298 of file utest.h.
UTEST_SKIP
#define UTEST_SKIP (msg)
Value:
  do {                                                                         \
    UTEST_PRINTF("   Skipped : '%s'\n", (msg));                                \
    *utest_result = UTEST_TEST_SKIPPED;                                        \
    return;                                                                    \
  } while (0)
Definition at line 749 of file utest.h.
UTEST_SNPRINTF
#define UTEST_SNPRINTF (...) snprintf(__VA_ARGS__)
Definition at line 435 of file utest.h.
UTEST_STATE
#define UTEST_STATE () struct utest_state_s utest_state = {0, 0, 0}
Definition at line 1715 of file utest.h.
UTEST_STREQ
#define UTEST_STREQ (x, y, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const char *xEval = (x);                                                   \
    const char *yEval = (y);                                                   \
    if (UTEST_NULL == xEval || UTEST_NULL == yEval ||                          \
        0 != strcmp(xEval, yEval)) {                                           \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : \"%s\"\n", xEval);                            \
      UTEST_PRINTF("    Actual : \"%s\"\n", yEval);                            \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 915 of file utest.h.
UTEST_STRNCMP
#define UTEST_STRNCMP (x, y, size) strncmp(x, y, size)
Definition at line 730 of file utest.h.
UTEST_STRNCPY
#define UTEST_STRNCPY (x, y, size) strncpy(x, y, size)
Definition at line 746 of file utest.h.
UTEST_STRNE
#define UTEST_STRNE (x, y, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const char *xEval = (x);                                                   \
    const char *yEval = (y);                                                   \
    if (UTEST_NULL == xEval || UTEST_NULL == yEval ||                          \
        0 == strcmp(xEval, yEval)) {                                           \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : \"%s\"\n", xEval);                            \
      UTEST_PRINTF("    Actual : \"%s\"\n", yEval);                            \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 941 of file utest.h.
UTEST_STRNEQ
#define UTEST_STRNEQ (x, y, n, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const char *xEval = (x);                                                   \
    const char *yEval = (y);                                                   \
    const size_t nEval = UTEST_CAST(size_t, n);                                \
    if (UTEST_NULL == xEval || UTEST_NULL == yEval ||                          \
        0 != UTEST_STRNCMP(xEval, yEval, nEval)) {                             \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : \"%.*s\"\n", UTEST_CAST(int, nEval), xEval);  \
      UTEST_PRINTF("    Actual : \"%.*s\"\n", UTEST_CAST(int, nEval), yEval);  \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 967 of file utest.h.
UTEST_STRNNE
#define UTEST_STRNNE (x, y, n, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const char *xEval = (x);                                                   \
    const char *yEval = (y);                                                   \
    const size_t nEval = UTEST_CAST(size_t, n);                                \
    if (UTEST_NULL == xEval || UTEST_NULL == yEval ||                          \
        0 == UTEST_STRNCMP(xEval, yEval, nEval)) {                             \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : \"%.*s\"\n", UTEST_CAST(int, nEval), xEval);  \
      UTEST_PRINTF("    Actual : \"%.*s\"\n", UTEST_CAST(int, nEval), yEval);  \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 994 of file utest.h.
UTEST_SURPRESS_WARNING_BEGIN
#define UTEST_SURPRESS_WARNING_BEGIN
Definition at line 700 of file utest.h.
UTEST_SURPRESS_WARNING_END
#define UTEST_SURPRESS_WARNING_END
Definition at line 701 of file utest.h.
UTEST_SURPRESS_WARNINGS_BEGIN
#define UTEST_SURPRESS_WARNINGS_BEGIN
Definition at line 1162 of file utest.h.
UTEST_SURPRESS_WARNINGS_END
#define UTEST_SURPRESS_WARNINGS_END
Definition at line 1163 of file utest.h.
UTEST_TEST_FAILURE
#define UTEST_TEST_FAILURE (1)
Definition at line 131 of file utest.h.
UTEST_TEST_PASSED
#define UTEST_TEST_PASSED (0)
Definition at line 130 of file utest.h.
UTEST_TEST_SKIPPED
#define UTEST_TEST_SKIPPED (2)
Definition at line 132 of file utest.h.
UTEST_TRUE
#define UTEST_TRUE (x, msg, is_assert)
Value:
  UTEST_SURPRESS_WARNING_BEGIN do {                                            \
    const int xEval = !!(x);                                                   \
    if (!(xEval)) {                                                            \
      UTEST_PRINTF("%s:%i: Failure\n", __FILE__, __LINE__);                    \
      UTEST_PRINTF("  Expected : true\n");                                     \
      UTEST_PRINTF("    Actual : %s\n", (xEval) ? "true" : "false");           \
      if (strlen(msg) > 0) {                                                   \
        UTEST_PRINTF("   Message : %s\n", msg);                                \
      }                                                                        \
      *utest_result = UTEST_TEST_FAILURE;                                      \
      if (is_assert) {                                                         \
        return;                                                                \
      }                                                                        \
    }                                                                          \
  }                                                                            \
  while (0)                                                                    \
  UTEST_SURPRESS_WARNING_END
Definition at line 867 of file utest.h.
utest_type_printer
#define utest_type_printer (...) UTEST_PRINTF("undef")
Definition at line 691 of file utest.h.
UTEST_UNUSED
#define UTEST_UNUSED UTEST_ATTRIBUTE(unused)
Definition at line 409 of file utest.h.
Typedef Documentation
utest_int64_t
typedef int64_t utest_int64_t
Definition at line 95 of file utest.h.
utest_testcase_t
typedef void(* utest_testcase_t) (int *, size_t)
Definition at line 379 of file utest.h.
utest_uint32_t
typedef uint32_t utest_uint32_t
Definition at line 97 of file utest.h.
utest_uint64_t
typedef uint64_t utest_uint64_t
Definition at line 96 of file utest.h.
Function Documentation
utest_fabs()
UTEST_WEAK double utest_fabs (double d)
Definition at line 1322 of file utest.h.
utest_fopen()
static FILE * utest_fopen (const char * filename, const char * mode) inline static
Definition at line 1424 of file utest.h.
References UTEST_NULL.
utest_isnan()
UTEST_WEAK int utest_isnan (double d)
Definition at line 1335 of file utest.h.
utest_main()
int utest_main (int argc, const char *const argv[]) inline static
Definition at line 1438 of file utest.h.
References utest_test_state_s::func, utest_test_state_s::index, utest_test_state_s::name, utest_state_s::output, utest_state_s::tests, utest_state_s::tests_length, UTEST_CAST, UTEST_COLOUR_OUTPUT, utest_fopen(), utest_ns(), UTEST_NULL, UTEST_PRId64, UTEST_PRINTF, UTEST_PRIu64, UTEST_PTR_CAST, utest_realloc(), utest_should_filter_test(), utest_state, UTEST_STRNCMP, UTEST_SURPRESS_WARNING_BEGIN, UTEST_SURPRESS_WARNING_END, UTEST_TEST_FAILURE, UTEST_TEST_PASSED, and UTEST_TEST_SKIPPED.
utest_mul_div()
static utest_int64_t utest_mul_div (const utest_int64_t value, const utest_int64_t numer, const utest_int64_t denom) inline static
Definition at line 337 of file utest.h.
utest_ns()
static utest_int64_t utest_ns (void) inline static
Definition at line 345 of file utest.h.
References UTEST_CAST, and utest_mul_div().
utest_realloc()
static void * utest_realloc (void *const pointer, size_t new_size) inline static
Definition at line 324 of file utest.h.
References UTEST_NULL.
utest_should_filter_test()
UTEST_WEAK int utest_should_filter_test (const char * filter, const char * testcase)
Definition at line 1358 of file utest.h.
References UTEST_NULL.
Variable Documentation
utest_state
struct utest_state_s utest_state extern